version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      - redis

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    depends_on:
      - redis
